random_state: 42
test_size: 0.3
target: Energy Consumption
categorical_features: ['Building Type', 'Day of Week']
numerical_features: ['Square Footage', 'Number of Occupants', 'Appliances Used', 'Average Temperature']

model_params:
  alpha: [0.0001, 0.001, 0.01, 0.05, 0.1]
  l1_ratio: [0.001, 0.05, 0.01, 0.2]
  penalty: ["l1", "l2", "elasticnet"]
  loss: ['squared_error', 'huber', 'epsilon_insensitive']
  fit_intercept: [False, True]